# Generated by Django 3.0.4 on 2020-06-21 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20200616_1553'),
        ('users', '0002_remove_user__active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified')),
                ('text', models.CharField(max_length=1000, verbose_name='текст комментария')),
                ('inner_status', models.CharField(choices=[('moder', 'moder'), ('on', 'on')], default='on', max_length=20, verbose_name='статус')),
                ('reply_to_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.TitleComment')),
                ('reply_to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_comment_replies', to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='titles.Title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TitleCommentRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('rate', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=20, verbose_name='оценка')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='users.TitleComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
