# Generated by Django 3.0.4 on 2020-06-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_titlecomment_titlecommentrate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='titlecommentrate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='titlecommentrate',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='titlecommentrate',
            name='user',
        ),
        migrations.DeleteModel(
            name='TitleComment',
        ),
        migrations.DeleteModel(
            name='TitleCommentRate',
        ),
    ]
