# Generated by Django 3.0.4 on 2020-06-26 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20200616_1553'),
        ('users', '0005_titlerating_viewedepisode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичный?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserListTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserList')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.Title')),
            ],
            options={
                'unique_together': {('list', 'title')},
            },
        ),
        migrations.AddField(
            model_name='userlist',
            name='titles',
            field=models.ManyToManyField(through='users.UserListTitle', to='titles.Title'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
