# Generated by Django 3.0.4 on 2020-08-02 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0001_initial'),
        ('users', '0009_auto_20200701_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_notification_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='push_notifications.PushNotificationSubscription'),
        ),
    ]
