# Generated by Django 3.0.4 on 2020-08-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_push_notification_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='push_notification_subscription',
        ),
    ]
