# Generated by Django 3.0.4 on 2020-08-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_push_notification_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionnotification',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='subscriptionnotification',
            name='notification_ptr',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='SubscriptionNotification',
        ),
    ]
