# Generated by Django 3.0.4 on 2020-08-03 10:09

import apps.core.fields
import apps.users.storages
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200803_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', apps.core.fields.BaseImageField(null=True, storage=apps.users.storages.UserImageStorage(), upload_to=apps.users.storages.user_image_path, verbose_name='avatar')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('sex', models.CharField(blank=True, choices=[('male', 'мужской'), ('female', 'женский'), ('other', 'другой'), ('animeshnik', 'анимешник')], max_length=30, null=True, verbose_name='пол')),
                ('about_myself', models.CharField(blank=True, default='', max_length=1000, verbose_name='о себе')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='about_myself',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
