# Generated by Django 3.0.4 on 2020-08-07 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200803_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', related_query_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
