# Generated by Django 3.1 on 2020-09-13 05:17

import apps.core.fields
import apps.users.storages
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200826_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=apps.core.fields.BaseImageField(blank=True, max_length=255, null=True, storage=apps.users.storages.UserImageStorage(), upload_to=apps.users.storages.user_image_path, verbose_name='avatar'),
        ),
    ]
