# Generated by Django 3.1 on 2020-09-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200920_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewedepisode',
            name='start_from',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Продолжить просмотр с (секунд)'),
        ),
    ]
