# Generated by Django 3.1 on 2020-09-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200927_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vk_id',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True, unique=True, verbose_name='VK ID'),
        ),
    ]
