# Generated by Django 3.0.4 on 2020-06-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20200616_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='_active',
        ),
        migrations.RemoveField(
            model_name='titlerelevantdata',
            name='_active',
        ),
        migrations.RemoveField(
            model_name='titlewatchorder',
            name='_active',
        ),
        migrations.RemoveField(
            model_name='watchorder',
            name='_active',
        ),
    ]
