# Generated by Django 3.0.4 on 2020-06-27 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20200616_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='relevant_data',
        ),
        migrations.RemoveField(
            model_name='titlerelevantdata',
            name='id',
        ),
        migrations.AddField(
            model_name='titlerelevantdata',
            name='title',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='relevant_data', serialize=False, to='titles.Title'),
            preserve_default=False,
        ),
    ]
