# Generated by Django 3.0.4 on 2020-06-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_watchorder_total_episodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchorder',
            name='title',
        ),
        migrations.RemoveField(
            model_name='watchorder',
            name='title_watch_order',
        ),
        migrations.DeleteModel(
            name='TitleWatchOrder',
        ),
        migrations.DeleteModel(
            name='WatchOrder',
        ),
    ]
