# Generated by Django 3.0.4 on 2020-07-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_auto_20200701_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'TV сериал'), (2, 'п/ф'), (3, 'OVA'), (4, 'ONA'), (5, 'спешл')], db_index=True, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='watchorder',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'TV сериал'), (2, 'п/ф'), (3, 'OVA'), (4, 'ONA'), (5, 'спешл')], null=True, verbose_name='type'),
        ),
    ]
