# Generated by Django 3.1 on 2020-09-13 05:17

import apps.core.fields
import apps.titles.models
import apps.titles.storages
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0011_auto_20200902_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='poster',
            field=apps.core.fields.BaseImageField(max_length=255, null=True, storage=apps.titles.storages.TitlePosterStorage(), upload_to=apps.titles.models.title_poster_path),
        ),
    ]
