# Generated by Django 3.1 on 2020-09-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0012_auto_20200913_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'тайтл', 'verbose_name_plural': 'тайтлы'},
        ),
        migrations.AlterModelOptions(
            name='titlewatchorder',
            options={'verbose_name': 'порядок просмотра', 'verbose_name_plural': 'порядки просмотра'},
        ),
        migrations.AlterField(
            model_name='title',
            name='type',
            field=models.CharField(blank=True, choices=[('series', 'TV сериал'), ('movie', 'п/ф'), ('ova', 'OVA'), ('ona', 'ONA'), ('special', 'спешл')], db_index=True, max_length=10, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='watchorder',
            name='type',
            field=models.CharField(blank=True, choices=[('series', 'TV сериал'), ('movie', 'п/ф'), ('ova', 'OVA'), ('ona', 'ONA'), ('special', 'спешл')], db_index=True, max_length=10, null=True, verbose_name='type'),
        ),
    ]
