# Generated by Django 3.1 on 2020-09-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0014_auto_20200919_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchorder',
            options={'ordering': ('ordering',), 'verbose_name': 'строка порядка просмотра'},
        ),
    ]
