# Generated by Django 3.1 on 2020-09-20 08:35

from django.db import migrations, models
from django.db.models.expressions import F

from apps.titles.models import Title as TitleModel


def populate_existing_rows_date_enabled(apps, schema_editor):
    Title = apps.get_model('titles', 'Title')
    db_alias = schema_editor.connection.alias
    Title.objects.using(db_alias).filter(
        inner_status=TitleModel.INNER_STATUSES.on
    ).update(date_enabled=F('date_created'))


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0015_auto_20200919_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='date_enabled',
            field=models.DateTimeField(
                editable=False, null=True, verbose_name='Дата активации'
            ),
        ),
        migrations.operations.RunPython(populate_existing_rows_date_enabled),
    ]
