# Generated by Django 3.1 on 2020-09-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0016_title_date_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='shikimori_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Shikimori ID'),
        ),
    ]
