# Generated by Django 3.1 on 2020-10-31 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0017_title_shikimori_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titlewatchorder',
            name='titles',
        ),
    ]
