# Generated by Django 3.1 on 2020-10-31 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0019_auto_20201031_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchorderitem',
            old_name='title_watch_order',
            new_name='watch_order_list',
        ),
    ]
