# Generated by Django 3.0.4 on 2020-06-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200622_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrate',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(0, 'дизлайк'), (1, 'лайк')], verbose_name='оценка'),
        ),
    ]
