# Generated by Django 3.1 on 2020-08-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0003_auto_20200803_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationsubscription',
            name='subscription',
            field=models.JSONField(verbose_name='Обьект подписки'),
        ),
    ]
