# Generated by Django 3.0.4 on 2020-06-16 04:56

import apps.core.fields
import apps.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('kodik', 'Kodik'), ('youtube', 'Youtube')], max_length=30)),
                ('model', models.SmallIntegerField(choices=[(0, 'none'), (1, 'translator'), (2, 'translation'), (3, 'title')], default=0)),
                ('internal_id', models.PositiveIntegerField(db_index=True, null=True)),
                ('external_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'resolver',
                'verbose_name_plural': 'resolvers',
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified')),
                ('slug', apps.core.fields.SlugField(blank=True, default='', max_length=255, validators=[apps.core.validators.slug_validator])),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'translator',
                'verbose_name_plural': 'translators',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='url')),
                ('external_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('service', models.CharField(choices=[('kodik', 'Kodik'), ('youtube', 'Youtube')], max_length=30, null=True)),
                ('is_other', models.BooleanField(default=False, verbose_name='Прочее')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', related_query_name='translation', to='titles.Title', verbose_name='title')),
                ('translator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='translations.Translator', verbose_name='translator')),
            ],
            options={
                'verbose_name': 'translation',
                'verbose_name_plural': 'translations',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='название эпизода')),
                ('url', models.URLField(max_length=255, verbose_name='url')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', related_query_name='episode', to='translations.Translation')),
            ],
            options={
                'ordering': ['number'],
                'get_latest_by': ['date_created'],
                'unique_together': {('translation', 'number')},
            },
        ),
    ]
