# Generated by Django 3.0.4 on 2020-08-07 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_auto_20200616_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('with_errors', models.BooleanField(default=False)),
                ('added_episodes', models.ManyToManyField(to='translations.Episode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
