# Generated by Django 3.0.4 on 2020-08-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='with_errors',
        ),
        migrations.AddField(
            model_name='update',
            name='without_errors',
            field=models.BooleanField(default=True, verbose_name='Updated without errors'),
        ),
    ]
