# Generated by Django 3.1 on 2020-09-27 06:47

from django.db import migrations, models


def populate_existing_rows_date_enabled(apps, schema_editor):
    Translator = apps.get_model('translations', 'Translator')
    db_alias = schema_editor.connection.alias

    for tr in Translator.objects.using(db_alias).all():
        if tr.name.strip().endswith('.Subtitles'):
            tr.name = f'Субтитры {tr.name.strip().replace(".Subtitles", "")}'
            tr.is_subtitles = True
            tr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0004_auto_20200808_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='is_subtitles',
            field=models.BooleanField(default=False, verbose_name='субтитры?'),
        ),
        migrations.RunPython(populate_existing_rows_date_enabled),
    ]
