# Generated by Django 3.1 on 2020-09-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0005_translator_is_subtitles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translator',
            options={'ordering': ('name',), 'verbose_name': 'translator', 'verbose_name_plural': 'translators'},
        ),
    ]
